### ISSUE TITLE
CCAPI Activation via Activation Tool fails

### ISSUE THREAD

**Issue by arturschwarz** [camerahacks/canon-api#2]
![renditionDownload](https://user-images.githubusercontent.com/10432739/126518190-3a788b25-8770-4992-ab27-6b0642fab107.png)

This is not an issue related to the code in this repo, it's rather a support request.

I've just bought a Canon EOS REBEL SL3 (i'm from Germany, here this model is called Canon EOS 250D) and wanted to activate the CCAPI feature on my camera.

Using the latest version 1.1.0c (and older versions) of the activation tool results in an unknown error and i was wondering if anyone could help me. 

The camera has the latest firmware (1.0.3) and i tried both Windows 10 and MacOS 11.4 (Big Sur). Same error which just says to contact the Canon Technical Support. Has anyone encountered this issue too?

**Comment by ccrystle** [comment]
The SL3 is only compatible with CCAPI v 1.0 as of 12/20. Perhaps if you used an even earlier version of the activation tool? And perhaps roll back the firmware?

**Comment by arturschwarz** [comment]
@ccrystle Thanks a lot for your answer! I will give it a shot!

**Comment by arturschwarz** [comment]
@ccrystle I've just tried activating CCAPI with version 1.0.0a. Still results in the mentioned error. Unfortunately this is the oldest version that i have access to via developer programme downloads in my region (Europe). Rolling back the firmware should not be an easy task since my EOS 250D was already shipped with firmware 1.0.3
